insert into sales_person values ('11','Aarav','Sharma')
insert into sales_person values ('12','Ananya','Patel')
insert into sales_person values ('13','Priya','Gupta')
insert into sales_person values ('14','Rohan','Iyer')
insert into sales_person values ('15','Sneha','Singh')
